name = "AutoExpe"
uuid = "7514acc9-c05b-434e-9853-2d72b8bb89c2"
authors = ["Zacharie Ales"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
